name: tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        eslint-version: [8.x, 9.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install ESLint ${{ matrix.eslint-version }}
      run: npm install eslint@${{ matrix.eslint-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
